# Command and announcement variables:
# [name]
# [uuid]
# [displayName]
# [world]
# [victimName]
# [victimUuid]
# [victimDisplayName]
# Command example:
# - money give [name] 1000
# Streaks - Executed once a player reaches the X kill, e.g. on the 5th kill
# Levels - Executed every Xth kill, e.g. every 3 kills
streaks:
  '5':
    enabled: false
    announcement: "[displayName] &cis on a roll!"
    commands:

# Executed every Xth kill
levels:
  '3':
    enabled: false
    announcement: "[displayName] &cis non-stop killing!"
    commands:

# If enabled, prevents players from killing the same player over and over again
# to increase number of kills and earn kill streaks
# Reset on logout
# E.g. below only counts killing the same player every minute
killAbuse:
  enabled: false
  # Maximum kills per duration per player
  maxKills: 1
  # time in seconds that a player killing another player they have already killed does not count towards a kill streak
  duration: 60