main: me.confuser.killstreaks.KillStreaks
name: KillStreaks
version: ${project.version}
authors: [ confuser ]
website: http://www.frostcast.net

commands:
  ksreload:
    description: 'Reloads KillStreak configs'
    usage: '/ksreload'
    permission: killstreaks.command.reload
  ksreset:
    description: 'Resets a player''s kill streak'
    usage: '/ksreset <player>'
    permission: killstreaks.command.reset

permissions:
  killstreaks.enabled:
    description: 'Allows player to have killstreaks'
    default: op
  killstreaks.announcements:
    description: 'Shows announcements'
    default: op
  killstreaks.command.reload:
    description: 'Allows reload of KillStreaks plugin'
    default: op
  killstreaks.command.reset:
    description: 'Allows resetting a player''s kill streak'
    default: op
